# Generated by Django 5.2.5 on 2025-09-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_image_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'مشتری'), ('SELLER', 'آرایشگر'), ('MANAGER', 'مدیر')], default='CUSTOMER', max_length=20),
        ),
    ]
