# Generated by Django 5.2.5 on 2025-09-04 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام آرایشگاه')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_salons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='شروع زمان مسدود')),
                ('end_datetime', models.DateTimeField(verbose_name='پایان زمان مسدود')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل مسدودی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='salons.salon')),
            ],
            options={
                'verbose_name': 'زمان مسدود شده',
                'verbose_name_plural': 'زمان\u200cهای مسدود شده',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='ظرفیت کل')),
                ('booked_count', models.PositiveIntegerField(default=0, verbose_name='تعداد رزرو شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='salons.salon')),
            ],
            options={
                'unique_together': {('salon', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlotBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل مسدودی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='salons.timeslot')),
            ],
            options={
                'verbose_name': 'مسدودی تایم اسلات',
                'verbose_name_plural': 'مسدودی\u200cهای تایم اسلات',
            },
        ),
        migrations.CreateModel(
            name='TimeSlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.PositiveIntegerField(default=60, verbose_name='فاصله زمانی بین نوبت\u200cها (دقیقه)')),
                ('capacity_per_slot', models.PositiveIntegerField(default=3, verbose_name='ظرفیت هر بازه زمانی')),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_config', to='salons.salon')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salons.salon')),
            ],
            options={
                'unique_together': {('salon', 'day_of_week')},
            },
        ),
    ]
