# Generated by Django 5.2.5 on 2025-09-08 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0004_alter_communicationwithus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationwithus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
