# Generated by Django 5.2.5 on 2025-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0005_communicationwithus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationwithus',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
