# Generated by Django 5.2.5 on 2025-09-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
