# Generated by Django 5.2.5 on 2025-09-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_service_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='service/default.png', null=True, upload_to='service'),
        ),
    ]
